apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-api
  labels:
    app: synergychat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-api
  template:
    metadata:
      labels:
        app: synergychat-api
    spec:
      containers:
        - name: synergychat-api
          image: 'localhost:5000/synergychat-api:latest'
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: synergychat-api-configmap
