apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-crawler
  namespace: crawler
  labels:
    app: synergychat-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-crawler
  template:
    metadata:
      labels:
        app: synergychat-crawler
    spec:
      volumes:
        - name: cache-volume
          emptyDir: {}
      containers:
        - name: synergychat-crawler-1
          image: "localhost:5000/synergychat-crawler:latest"
          imagePullPolicy: Never
          volumeMounts:
            - name: cache-volume
              mountPath: /cache
          envFrom:
            - configMapRef:
                name: synergychat-crawler-configmap
        - name: synergychat-crawler-2
          image: "localhost:5000/synergychat-crawler:latest"
          imagePullPolicy: Never
          volumeMounts:
            - name: cache-volume
              mountPath: /cache
          envFrom:
            - configMapRef:
                name: synergychat-crawler-configmap
          env:
            - name: CRAWLER_PORT
              value: '8081'
        - name: synergychat-crawler-3
          image: "localhost:5000/synergychat-crawler:latest"
          imagePullPolicy: Never
          volumeMounts:
            - name: cache-volume
              mountPath: /cache
          envFrom:
            - configMapRef:
                name: synergychat-crawler-configmap
          env:
            - name: CRAWLER_PORT
              value: '8082'
