apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:OCXZrgPEkJyBYndZsILUEGJXdNpomM8ZD1zJ7FHArU2ryWNO1ctMDg2MS/qmX8eefmzGS/eG2Ae8FZG6vlzOGTabH1khdqtGI63f0lxgz+TbNATIUsoshFBGEGWGDSN/btLuCq47NMumvpwpcmbufhbmvtqPuDL4su2nmX9+JR1EscxzqTbYZVC+sJX6eZQtfcw4oneHeILOvXhzNdRbyXb7KzKyF2vrDCOX5aY3NLNuUxOp80iUYgx2I8tKZCtdrWAWZuo1jzgFShCzroaAEZWh2JhdRzIs1SRuHA==,iv:07eBeF5jnL+HS6++8CoX8PETB1Aaf8wLSqoMei9OQek=,tag:6G7+yi72xsd4357zTDSOFQ==,type:str]
kind: Secret
metadata:
    name: postiz-x-cookie-bridge-ghcr
    namespace: postiz
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTalNCWXJDZitBU2V2T3RM
            WHhIQ05Uam5sOVc5cXJIa2p2VVBCSUdxRm0wCmkzUUdzbXphYmQ4U0g0ck9ZTTFM
            d3Y4Vm1xSUtTamdmL2JCY3ErVXhzQk0KLS0tIGp4aDh3RVBkYkplK3F0QWVpblJt
            NUNCbGUvWDlaRmZHWTE2OEh3VURBaEkK0CN/1X5La4HXxTcTw1jU/xoahMeqSmz+
            J6blo2/zcLPwhFAJKExqSS97GFkzvC0saXbYYNj0bh39gobNvBLUGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T11:00:26Z"
    mac: ENC[AES256_GCM,data:+ggW+Vr3Rh+YJ9z0dCDjClRpDgZC/OUAJV5CHy5pQGM6dSXzyMhG7IntRFhLIPqjNBzqmrS8B0C9TEqJBLTCbubvkhE7IQa0t7YEhMGbr/hQey6T899CaJwVogkcfqYC7DcYLI4Y5qYLU9fJ2oVbuYXZhK/an/krOlov8M1qJAA=,iv:7P0FDgpogtI88MIJPtNhfOx3NL4Jw3690epYu9CW9O4=,tag:sFqtpRgLZOqWl297vnrYtQ==,type:str]
    version: 3.13.1
