apiVersion: v1
kind: Secret
metadata:
    name: postiz-x-cookie-bridge
    namespace: postiz
type: Opaque
stringData:
    TWITTER_AUTH_TOKEN: ENC[AES256_GCM,data:dYEj+XUs5YSvuf449ndXUPF8XXoEmKO0nSY/jemMOICL83e/cwF/8Q==,iv:GQcW7AckePRPV1kbC+hTSp8Amn1z9uesFO5TrhlrvLA=,tag:fi9M9W+6lCtsxk5d/16x6Q==,type:str]
    AUTH_TOKEN: ENC[AES256_GCM,data:M6B29DMZDVaPdi32sKKEx8kjOeP0acx++cYOfNrEukbyRc1+U6zqZQ==,iv:553T2/5G6XSji1vBR0OxY3enSkY2hs1NkkRUpmVuQvg=,tag:tn1+38EjsFOSBVISojOeog==,type:str]
    POSTIZ_X_BRIDGE_TOKEN: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RnAxZ2o1dUpac2J6M2ZT
            YlJXSGFzckRPOFlSd0R2eC9SRm9PRmE4TkJzCjlxQlBlN3Y3UFVTaVlNZ0xodjhK
            WkpwM1R0VUNjelRmZHNUdFFGSFNTOWsKLS0tIDlqU1hTNUFEUDRPcGh0YWN5UmtE
            NTNBb243UFU3WFFabWl4TFY4VEZzUzAKVZO4ix2z5hO0mNYhVJpTAWTlnAwQWAHs
            +rkOfmvlLpAZ7N8FxNi7nCsfagHXnF+O2eJkBer1kUZNWXAEYuC9iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T10:54:01Z"
    mac: ENC[AES256_GCM,data:On1uMFRwWHYok1OS8tcbv31HBKLBEPijPKxGQ2qUWTZ94zt1d2AV+86DnRIAbB4c+edYo3xQbohmx0F4ohyqTXzx59JJH3huVG4JezbOv2P47Yh+NcKPoeHa6UKjQczp6T+8+qoCHIYQiirigtS10HutczXuhAIWxa9J4fFoRWU=,iv:7hNxkxv2Bfwi2PeUMTNwwdetPmqOfkLLFsted+qebSw=,tag:JEKHrb4pepdTSpYk+50W/Q==,type:str]
    version: 3.13.1
