# Before this please install ingress-nginx and then start this process since that would be really beneficial.
# checkout the cert-manager site and get the latest install command for your specific cloud requirements
# for gke: https://kubernetes.github.io/ingress-nginx/deploy/#gce-gke
# for cert-manager: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.yaml
#
# Demo Deployment for starting
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kube-certs
#   namespace: demo
# spec:
#   selector:
#     matchLabels:
#       app: kube-certs
#   template:
#     metadata:
#       labels:
#         app: kube-certs
#     spec:
#       terminationGracePeriodSeconds: 5
#       containers:
#       - name: server
#         image: saiyam911/kube-certs:sha-848915f
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 8080
#         env:
#         - name: PORT
#           value: "8080"
# ---
# # Demo Service for starting
# apiVersion: v1
# kind: Service
# metadata:
#   name: kube-certs
#   namespace: demo
# spec:
#   selector:
#     app: kube-certs
#   ports:
#   - name: http
#     port: 80
#     protocol: TCP
#     targetPort: 8080
#   type: NodePort
# ---
# Actual cert-manager starts here
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kube-issuer
  namespace: harbr
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: bupdprasanth@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: kube-issuer
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
---
#
# Certificate issuer starts here
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubecert
  namespace: harbr
spec:
  secretName: harbor-cert
  issuerRef:
    name: kube-issuer
    kind: ClusterIssuer
  commonName: regg.bupd.xyz
  dnsNames:
  - regg.bupd.xyz
---
# #
# # Certificate ingress config starts here
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     cert-manager.io/cluster-issuer: kube-issuer
#     kubernetes.io/ingress.class: nginx
#   name: kube-certs-ingress
#   namespace: harbr
# spec:
#   rules:
#   - host: regg.bupd.xyz
#     http:
#       paths:
#       - backend:
#           service:
#             name: harbor
#             port:
#               number: 80
#         path: /
#         pathType: Prefix
#   tls:
#   - hosts:
#     - regg.bupd.xyz
#     secretName: harbor-cert
#
