apiVersion: v1
kind: Pod
metadata:
  name: busyboxes
spec:
  serviceAccountName: harbor-sa
  automountServiceAccountToken: true
  containers:
  - name: busyboxes
    image: demo.goharbor.io/library/alpine:latest
    command: ["sh", "-c", "sleep 3600"]
  volumes:
  - name: sa-token
    projected:
      sources:
      - serviceAccountToken:
          path: token
          audience: demo.goharbor.io
