apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: debugging-psp
spec:
  privileged: true
  allowedCapabilities:
  - SYS_PTRACE
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - "*"
