apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-ingressroute-certificate
  namespace: harbor
spec:
  secretName: harbor-cert
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - registry.reg.bupd.xyz
