apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: harbor-ingressroute
  namespace: harbor
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`registry.reg.bupd.xyz`)
    kind: Rule
    services:
    - name: harbor
      port: 80
  tls:
    secretName: harbor-cert
