apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: web-depl
spec:
  rules:
  - host: web-depl
    http:
      paths:
      - backend:
          service:
            name: web-depl
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
