# this config file contains all config fields with comments
# NOTE: this is not a particularly useful config file
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4


featureGates:
  "KubeletServiceAccountTokenForCredentialProviders": true

# patch the generated kubeadm config with some extra settings
# kubeadmConfigPatches:
# - |
#   apiVersion: kubelet.config.k8s.io/v1beta1
#   kind: KubeletConfiguration
#   evictionHard:
#     nodefs.available: "0%"
# kubeadmConfigPatches:
# - |
#   apiVersion: kubeadm.k8s.io/v1beta3
#   kind: InitConfiguration
#   nodeRegistration:
#     kubeletExtraArgs:
#       image-credential-provider-bin-dir: "/usr/local/bin/k8s-credential-providers"
#       image-credential-provider-config: "/etc/kubernetes/credential-provider-config.yaml"
# patch it further using a JSON 6902 patch
# kubeadmConfigPatchesJSON6902:
# - group: kubeadm.k8s.io
#   version: v1beta3
#   kind: ClusterConfiguration
#   patch: |
#     - op: add
#       path: /apiServer/certSANs/-
#       value: my-hostname
# 1 control plane node and 2 workers
nodes:
# the control plane node config
- role: control-plane
# the workers
- role: worker
- role: worker
