apiVersion: v1
kind: Service
metadata:
  annotations:
    cert-manager.io/cluster-issuer: kube-issuer
    cloud.google.com/neg: '{"ingress":true}'
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: harbr
    meta.helm.sh/release-namespace: harbr
  creationTimestamp: "2025-01-06T08:52:28Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: harbor
    app.kubernetes.io/instance: harbr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    app.kubernetes.io/part-of: harbor
    app.kubernetes.io/version: 2.12.0
    chart: harbor
    heritage: Helm
    release: harbr
  name: harbor
  namespace: harbr
  resourceVersion: "82805"
  uid: a680d1d0-b05e-465c-962f-f8b311deb5be
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.236.118
  clusterIPs:
  - 34.118.236.118
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 32609
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 31250
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: harbor
    component: nginx
    release: harbr
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.60.20.232
      ipMode: VIP
