apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-certs
  namespace: static-website
spec:
  selector:
    matchLabels:
      app: kube-certs
  template:
    metadata:
      labels:
        app: kube-certs
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: saiyam911/kube-certs:sha-848915f
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-certs
  namespace: static-website
spec:
  selector:
    app: kube-certs
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: static-website-tls
  namespace: static-website
spec:
  secretName: static-website-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: test.bupd.xyz
  dnsNames:
  - test.bupd.xyz
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  name: kube-certs-ingress
  namespace: static-website
spec:
  rules:
  - host: test.bupd.xyz
    http:
      paths:
      - backend:
          service:
            name: kube-certs
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - test.bupd.xyz
    secretName: static-website-tls
