apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: static-website
  name: static-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: static-website
  type: LoadBalancer
status:
  loadBalancer: {}
