apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gc-ingress
  namespace: "{{ .Values.namespace }}"
spec:
  ingressClassName: nginx
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - backend:
              service:
                name: "{{ .Values.service.name }}"
                port:
                  number: {{ .Values.service.port }}
            path: /
            pathType: Prefix
