apiVersion: v1
kind: Secret
metadata:
    name: postiz-linkedin-cookie-bridge
    namespace: postiz
type: Opaque
stringData:
    LINKEDIN_LI_AT: ENC[AES256_GCM,data:7haPfZrzkekmC4AYu+nr7FL1tZTbAUJYUcM47MGYMUkXv46B5RG0Yb2xR13v9Vj8P+iEyZTgwtiDpzXy5pQTJv3o/WHdJqMP7MJ82cwvEUbwvvv3GcasQAjdg+Qd6yI13J2AsyMafZX0N060LpAxgi/daZB4kG/mdX63/5BqaSDw1WXVsbR9DnXs+147vVsPSG+40WRwHWA=,iv:/1g5O4sD/h37e9eP4zrhHU9AaQoldC2RV58J7R77/nM=,tag:o6FBjXH/wDUptpn+7A5CSA==,type:str]
    LINKEDIN_JSESSION_ID: ENC[AES256_GCM,data:q9c2ihvNtF13ah6ciRayCA1CW+oxFWR7,iv:BvISOBWvkPLXMP7KZUX1lPkYymlloKgjgwfwEk1Agao=,tag:NACOHsuwMhCT0LUhOyV5CA==,type:str]
    POSTIZ_LINKEDIN_BRIDGE_TOKEN: ENC[AES256_GCM,data:Ce/fNNPqdWsRf4fN34CL/2MCKaoZiryIc9LHCIkZvTHEy8HF5TkMeiFW2i62CZa6hCTF4VrLYJTPDb0XbaYsyw==,iv:voZXH89MgXFrzqiaGksxLMezu38hwHpSLowi0zcl7cM=,tag:5/bGjbth3vITdOihYG9gUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWmxLSXlYS0hQUnAyQ3lR
            T2IzNmt6MkM1bmlpVFhHbFJ5bGw3cmsrRENBCnhXZUxTdlFjbkVkQ2ZGaWpmTWx0
            dmtpcGVUeFFDNDVidlorbmNoUEh5Z0kKLS0tIGNITDhkMHh3YUNVMXdpNlFUZE55
            a3FnWGpab3pybUIrbzdPWVNCYjJ3c2sKBiY9fvxOQZ7tew8+SbVZgT4nkdxqe9EA
            g0OpQv5iGwS8s8O9tphbHIkXlbyGDF81aPD0mQIOkAYA8tkedndf7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T10:31:46Z"
    mac: ENC[AES256_GCM,data:uJciHRy02dVdDomV+g4T7zukfjEQ4svnATE2X3hIO0Wde9o+weVlEDrt2hLlaEGSdMQ4Bug4oXxcj45Z+8MKLL+1Y6yOLPMBQy4bRLUHCm92wL//fhMNdEnimQ/8RAKn0HfOJ7OTCeFSfyUXJtc7+uQvS+00lPHSFwXPdazrAv0=,iv:soJb35+CKoKOihX1smkAHudxCs6WMYGvOK7m16Lmzxc=,tag:Yqzxf1qg6MXtU2dkptK2Pg==,type:str]
    version: 3.13.2
