apiVersion: v1
kind: Secret
metadata:
    name: postiz-linkedin-cookie-bridge
    namespace: postiz
type: Opaque
stringData:
    LINKEDIN_LI_AT: ENC[AES256_GCM,data:BCbB+df8rVKez423pINfG0XsOzZ+MkFyKSHvoUnheG3dsCqKFCPbs/1EHq/6nBsy/rnqniorM8NAOg+rHpr1H+V89NkSSq9zTgein5vdeWZvd7fhS/dX/hLUs926cGl+LaPQnvdwTIhpYPChsMh2n22d2b6WH/6k4+YHy5l9I+NFrM1nU87Ut09zLIfCTQVkdx33LMWOhEY=,iv:xnNw3IyE5r9I+ZStz1pyrXgb4XeSSIzKTDXVeI8J6aE=,tag:jIGiBEdsycxEWk/CAHhidg==,type:str]
    LINKEDIN_JSESSION_ID: ENC[AES256_GCM,data:SL4sKvd4Oh5VOmvURjkN4VO+Nn2+Ho9X,iv:DlqnrACQXdUAzqBGb3b8fI/7rlxBzOm63ZzXlaQ9N1o=,tag:5ZY0iftaVEca4fOt/6gX8w==,type:str]
    POSTIZ_LINKEDIN_BRIDGE_TOKEN: ENC[AES256_GCM,data:Ce/fNNPqdWsRf4fN34CL/2MCKaoZiryIc9LHCIkZvTHEy8HF5TkMeiFW2i62CZa6hCTF4VrLYJTPDb0XbaYsyw==,iv:voZXH89MgXFrzqiaGksxLMezu38hwHpSLowi0zcl7cM=,tag:5/bGjbth3vITdOihYG9gUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWmxLSXlYS0hQUnAyQ3lR
            T2IzNmt6MkM1bmlpVFhHbFJ5bGw3cmsrRENBCnhXZUxTdlFjbkVkQ2ZGaWpmTWx0
            dmtpcGVUeFFDNDVidlorbmNoUEh5Z0kKLS0tIGNITDhkMHh3YUNVMXdpNlFUZE55
            a3FnWGpab3pybUIrbzdPWVNCYjJ3c2sKBiY9fvxOQZ7tew8+SbVZgT4nkdxqe9EA
            g0OpQv5iGwS8s8O9tphbHIkXlbyGDF81aPD0mQIOkAYA8tkedndf7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T11:58:39Z"
    mac: ENC[AES256_GCM,data:gFFEf4fabOI/yu4d0o49gXI8q6oZCH77oXzlu4mqH74qlPH1T3GUieXCv8OiV5kc2VhyG0my3G2SM+xT50XEtByjT+OgVgFlHDudjy2pn9CvCXafPzT6HhaUaedBxJdNyZwohii2MsQElwX56IOIS5S0K7HW4zSv/xh4nLBDlqI=,iv:V4h/0TYcSm6GNm1t2qIG5Jr3u44Ss4gWvhwlQapuW40=,tag:Kd/3839OQphEzageNkIv2Q==,type:str]
    version: 3.13.2
