apiVersion: v1
kind: Secret
metadata:
    name: postiz-linkedin-cookie-bridge
    namespace: postiz
type: Opaque
stringData:
    LINKEDIN_LI_AT: ENC[AES256_GCM,data:v3MJlbeGciGW8GCgtNuO0FIARTIh8XuJwoZs8JiV4xrFA261yKLCcOpEolHP3BIfLjXUdqeC+kRqFcmMVKzTbSLktmb0gMwJSfuPyPuacRu70E056HFvM1HHzV2rljQi+wNh+A0h6el84+L2HnisfmkdkoQv6fJV1D1fkndpIifox/FrW0LwKpdr8ZbpKevl0SVPxDBapYg=,iv:CZRt3antefnyr2P+C/oNmwIC/2grecQxLlGQNhOvux8=,tag:UyrO/DNyMD6H/fxE6PbxEQ==,type:str]
    LINKEDIN_JSESSION_ID: ENC[AES256_GCM,data:q9c2ihvNtF13ah6ciRayCA1CW+oxFWR7,iv:BvISOBWvkPLXMP7KZUX1lPkYymlloKgjgwfwEk1Agao=,tag:NACOHsuwMhCT0LUhOyV5CA==,type:str]
    POSTIZ_LINKEDIN_BRIDGE_TOKEN: ENC[AES256_GCM,data:Ce/fNNPqdWsRf4fN34CL/2MCKaoZiryIc9LHCIkZvTHEy8HF5TkMeiFW2i62CZa6hCTF4VrLYJTPDb0XbaYsyw==,iv:voZXH89MgXFrzqiaGksxLMezu38hwHpSLowi0zcl7cM=,tag:5/bGjbth3vITdOihYG9gUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWmxLSXlYS0hQUnAyQ3lR
            T2IzNmt6MkM1bmlpVFhHbFJ5bGw3cmsrRENBCnhXZUxTdlFjbkVkQ2ZGaWpmTWx0
            dmtpcGVUeFFDNDVidlorbmNoUEh5Z0kKLS0tIGNITDhkMHh3YUNVMXdpNlFUZE55
            a3FnWGpab3pybUIrbzdPWVNCYjJ3c2sKBiY9fvxOQZ7tew8+SbVZgT4nkdxqe9EA
            g0OpQv5iGwS8s8O9tphbHIkXlbyGDF81aPD0mQIOkAYA8tkedndf7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T02:25:29Z"
    mac: ENC[AES256_GCM,data:/PTAznGmstjLiIGgnkVzsgDSmLn8uEq5NZBzyM8ykxNHLTGKTAKEbOWxwY1xgo3XQ+6ACyXk/Yh5BLYxzpbN/xuJKwGdlA1jEdcLHKPb91kgIXsfFqhETTgLnVScmpg93vE41nIaKxZNmxWsAuXd9r77yHIcWVm2oh3fqQPz9X4=,iv:vyLUlcSAO1aejKf2zh/9ntchvriKT7XtiR9PxMtQKdQ=,tag:445HCA9ESCL0GNlB2V4Uew==,type:str]
    version: 3.13.2
