version: '3.7'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    labels:
      - traefik.enable=false

  keycloak:
    image: local/keycloak:17.0.0
    build:
      context: .
    command: start
    expose:
      - 8080
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: localhost:8098
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      PROXY_ADDRESS_FORWARDING: "true"
    depends_on:
      - postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak.entrypoints=web
      # - traefik.http.routers.keycloak.rule=Host(`localhost`)
      # - traefik.http.routers.keycloak.tls.certresolver=myresolver
