apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:q18Z7daXhTEyFeGkIl004JNpaOEG9IUZYtULuF5xGO7c/WlhBDrkMcFQh3PJ/dskjbdxfHuclpZFI/tsBPGYOQ==,iv:vNG3wPXS1u9PR/KzXS3lO77vdAOyBpG7VSRCnHaLUaE=,tag:tPeKjBMW9ci9Va3muciugQ==,type:str]
    admin-user: ENC[AES256_GCM,data:7s6aP4zwzrUjWBDxqhekbdpdFS+KxstA,iv:A35Gzf4mHTid1kmNXJ2SVj4bcUFtpw1AobQJ75qO+G8=,tag:sOjLVqtB4MOWIK0grtXnkQ==,type:str]
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTUN5SnhNU1Z4bHJ6NHc0
            NEM3Nnk3UHFqbTBZWDBOelNZeU4rdFJDRG5zCmhJK2ZoQmk4N2xrTjhHaWhycFJB
            QnhjazJJeDBsU2lPSDFtN1dvY2lkbDgKLS0tIG1RMWs2ZlZoZzBGUG80enp5ZFdE
            cUlML1pmSFIzNnBFV1pDUUlkT0lMRVUKDfxXeUUgezXuZV386XaAP7h7NPStRML1
            yaFP6WAsN7k0XnLbnpsgnxPmf7Z++U6O9Wcof8Rn8Q3BKdTuaSojRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T10:25:45Z"
    mac: ENC[AES256_GCM,data:9Ah65c8aAe+Z22vH5qWSWnEAejRKQ4989cof7AaxHO1GnB9/KoTX9MtC37O3a1e1GhioPDlSxx9+iuhkmauVqmrqDxLimAUjW1+JPFVB7e7hKvlJ/RR4k2Aq3ERJ9A83koRrme8rtMACNo78GXTilYpyHZBqJW2COngedtJwGqQ=,iv:MdjDUpQHKaBxu3j8POnH1rYAtvoAxPavizVpRDIlEBU=,tag:JqA2R5Hz1HKMUySoWqPtPA==,type:str]
    version: 3.13.1
