apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - grafana-admin-secret.yaml
  - prometheus-stack-values-configmap.yaml
  - grafana-dashboard-harbor-configmap.yaml
  - prometheus-community-helmrepository.yaml
  - kube-prometheus-stack-helmrelease.yaml
