# Default values for Ground Control Helm chart

# Image configuration
image:
  repository: "8gears.container-registry.com/harbor-satellite/ground-control"
  tag: "latest"
  pullPolicy: "Always"
  initcontainers:
    repository: "8gears.container-registry.com/harbor-satellite/db-migrator"
    tag: "latest"

# Image pull secrets (for private Docker registry)
imagePullSecrets:
  - name: "8gears-cr-cred"

# Deployment configuration
replicaCount: 1

# Environment variables for the Ground Control Go app
env:
  DB_HOST: "postgres" # Update with the DB host
  DB_PORT: "5432" # Update with the DB port
  DB_DATABASE: "groundcontrol" # Update with the DB name
  DB_USERNAME: "postgres" # Update with the DB username
  DB_PASSWORD: "password" # Update with the DB password
  APP_ENV: "local"
  AIR_TOML_LOG_LEVEL: "debug"
  PORT: "8080" # Ensure PORT is set here
  HARBOR_USERNAME: "admin" # Add Harbor credentials
  HARBOR_PASSWORD: "Harbor12345"
  HARBOR_URL: "https://harbor-sat.bupd.xyz"

# Service configuration
service:
  name: "gc"
  port: 80
  targetPort: 8080
  type: ClusterIP # Can be NodePort or LoadBalancer if needed

# Ingress configuration
ingress:
  enabled: true
  host: "gcc.kube.bupd.xyz"
  tls: false # Disable TLS

# Namespace for resources
namespace: "grounded"

# for postgres dependency
postgresql:
  fullnameOverride: postgres
  image:
    tag: 17
  auth:
    password: password
    username: postgres
    database: groundcontrol

  commonLabels:
    name: postgres
    component: database
    manager: helm

# Values for the deployment of the configmap for the postgresql
configmap:
  name: postgres-configmap

# Values for the deployment of your app
app:
  name: ground-control
  component: frontend
  manager: helm

initContainers:
  name: check-db-ready
  image: postgres:17
  command: [
      "sh",
      "-c",
      "until pg_isready -h postgres -p 5432;
      do echo waiting for database; sleep 5; done;",
    ]
