apiVersion: v1
data:
    INSTAGRAM_SESSION_ID: ENC[AES256_GCM,data:I/BcgawizXwMBBJ5qFUVtf8uh47vbnPNpgWi5KWwIvWTy5V+S1g0cTCsf1Z/YibPy/fD7gTDBiWW7PojPhPT0a/Kq1BUVQVvlQAXqgQ4naV19ArjeVw7zWw88MirAG9eO7pEDwE4aAY=,iv:O/JwPbgXZzIbi+3KXIk5lRpIw0o4xDnwBoWqROcEeXs=,tag:h/tcVc9mP8duOoKTdA+b0g==,type:str]
    POSTIZ_INSTAGRAM_BRIDGE_TOKEN: ENC[AES256_GCM,data:iG8hLeSN43TFxam0HEuK+nKxbZB6NZQgBFyrbP+yH/9Qs7q2/lzgtXg/MUQfEz/4N86VethVlUiHe3C6vgwk1/95aWBzV0tU0w628zUO41/lO0qZ5HmLuA==,iv:8NrkTm2n2YNcR0yhbptClFv5+9iT8nZss/dpytHMOSo=,tag:Pw1DZFPAvA9djIYZpBYeoA==,type:str]
kind: Secret
metadata:
    name: postiz-instagram-session-bridge
    namespace: postiz
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUE00c2UveDdZZ2J0dTZ5
            RUg1d21NSXh0OU85QlhrWmdkMzBaN1VWZDBzClZ0RThsZWtOcDRKM0M5QWZ4NGRH
            Rlluby9iUG5kbGQ0d1dRbWh2a0RWVWMKLS0tIFZDK292cG5hNXN0UDh2RFlvMlZx
            OExrS2ZGSmpyeThSQXJyNkNxTUJ3bkUKF2Ky09MqhWykxuSkhpBYrJyq3HCOhizr
            hTIuRy5WWzciMUCQZOJdLAko5nW1yl7CoVk2iLeo7lL+qqgBz1uDHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T07:07:41Z"
    mac: ENC[AES256_GCM,data:Y963u060TnJcIZ+DHi9f7ljGUSCWxdSlm8sQtUiZsQ8v87bQXC0JwwDl9Rl4VF7i7i7bBvARKeMtWSZEICfVDex9gT7svo2A+cuiLTzXAD/Q/1ub5+YKoJbfp+zqBg+up2ReZkdZ/yf5iKXp4HfTaCKMcREOLY/ZemqG1c9wp+0=,iv:XXrBsnwnzC1aVqkaxl6koRfnBZN7q7RNWOpncnYKiGM=,tag:9zaAn9oQ/OjhX2zLP2eY+Q==,type:str]
    version: 3.13.1
