apiVersion: v1
data:
    INSTAGRAM_SESSION_ID: ENC[AES256_GCM,data:rop/Eqr/UGTXMDywQ1UvuG9207dV+lbcDc/qkUeupqwI/C7zipxid1qqFGE7Te0v1O+QQrV0pyvfxVUdTeQosW6EvF3avKOioWkO+vq9Mncuehvze8BPY779nh4D2N+jHq5zmGO5p9M=,iv:JfrXNnGXTnquLDcDv+sQ+o0DGhELgjDfsvRISIVvcN8=,tag:NjpWuo95QZNKDJGP1ftlnw==,type:str]
    POSTIZ_INSTAGRAM_BRIDGE_TOKEN: ENC[AES256_GCM,data:iG8hLeSN43TFxam0HEuK+nKxbZB6NZQgBFyrbP+yH/9Qs7q2/lzgtXg/MUQfEz/4N86VethVlUiHe3C6vgwk1/95aWBzV0tU0w628zUO41/lO0qZ5HmLuA==,iv:8NrkTm2n2YNcR0yhbptClFv5+9iT8nZss/dpytHMOSo=,tag:Pw1DZFPAvA9djIYZpBYeoA==,type:str]
kind: Secret
metadata:
    name: postiz-instagram-session-bridge
    namespace: postiz
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUE00c2UveDdZZ2J0dTZ5
            RUg1d21NSXh0OU85QlhrWmdkMzBaN1VWZDBzClZ0RThsZWtOcDRKM0M5QWZ4NGRH
            Rlluby9iUG5kbGQ0d1dRbWh2a0RWVWMKLS0tIFZDK292cG5hNXN0UDh2RFlvMlZx
            OExrS2ZGSmpyeThSQXJyNkNxTUJ3bkUKF2Ky09MqhWykxuSkhpBYrJyq3HCOhizr
            hTIuRy5WWzciMUCQZOJdLAko5nW1yl7CoVk2iLeo7lL+qqgBz1uDHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T10:50:16Z"
    mac: ENC[AES256_GCM,data:FsJjruyTGGX9hTiqD4LpsmzfjVIEb+dxutoNpxkD55ILL3l4O0VdWnGRGLTytwjJV8AhrR9rc9vtEo5YTcVGev27mpu3SYUYnZwiVYua/SREi2WXmATMw5BM6PuBphPF+bVDSWq/ruuaHq34GmD2UxYsAckrklk2VdVVGqUggRY=,iv:ghjzS5FZgWVSVvvBVFGdlPwaidNeb7Sn49tP2poEXnU=,tag:sG7iVyW52xDuod1rxC5lqQ==,type:str]
    version: 3.13.1
