apiVersion: v1
data:
    INSTAGRAM_SESSION_ID: ENC[AES256_GCM,data:wBUSU3slhNBKz2vQUzdLy9WV9xpcdlm5wb7h2jCHyCD5OgfvUsfjWRCzdbDFvAZgm/0px1Gyht5ZL3GMfZ4JkbtvlN+c6k6j/ilsbdsE/5OsFLYqyvm0a3LhhD4YnOodcfO49wbSyvI=,iv:FnpmMxRCU8ZoS2LvIXMgBkucpjD7v5nOLe/CYmxYf4E=,tag:xfxya0qfYTDecdcLx4leLw==,type:str]
    POSTIZ_INSTAGRAM_BRIDGE_TOKEN: ENC[AES256_GCM,data:iG8hLeSN43TFxam0HEuK+nKxbZB6NZQgBFyrbP+yH/9Qs7q2/lzgtXg/MUQfEz/4N86VethVlUiHe3C6vgwk1/95aWBzV0tU0w628zUO41/lO0qZ5HmLuA==,iv:8NrkTm2n2YNcR0yhbptClFv5+9iT8nZss/dpytHMOSo=,tag:Pw1DZFPAvA9djIYZpBYeoA==,type:str]
kind: Secret
metadata:
    name: postiz-instagram-session-bridge
    namespace: postiz
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUE00c2UveDdZZ2J0dTZ5
            RUg1d21NSXh0OU85QlhrWmdkMzBaN1VWZDBzClZ0RThsZWtOcDRKM0M5QWZ4NGRH
            Rlluby9iUG5kbGQ0d1dRbWh2a0RWVWMKLS0tIFZDK292cG5hNXN0UDh2RFlvMlZx
            OExrS2ZGSmpyeThSQXJyNkNxTUJ3bkUKF2Ky09MqhWykxuSkhpBYrJyq3HCOhizr
            hTIuRy5WWzciMUCQZOJdLAko5nW1yl7CoVk2iLeo7lL+qqgBz1uDHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T07:39:27Z"
    mac: ENC[AES256_GCM,data:aEpzPO9u6q4MdBKXjTGxZhfaX5qrlGRvf8JeD0ElZINfMAXbhG+bflGe2icuj6LRJt3D+N/w1GPWW/0DaqqjgVn2roUEuVozyGFdEuqJtSoLqqYCyOJcRI9qyaebwzEI0LsPfBqizBBUeJHF4MN84nE/2y4E/S+NKqr2fbW6wVU=,iv:mOcEjHCGvkR8ZioU5FbOyxXSSokQXY7abc3djoVGle0=,tag:/AxcmNhOcrJQLiZdNitXFw==,type:str]
    version: 3.13.1
