apiVersion: v1
kind: Secret
metadata:
    name: postiz-helm-values
    namespace: postiz
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:Md++muPAoxaAGI5M8z7Mpu6zF5OQCQhlXSdRP7PMxdrNmjA/jE7ChshZkyf/na1OYs8ywsuxuBhK43fILRYjtmYuePFa5B+omO/0c8Hq7ZpzfFaXqDU+ID68uk41nVEMSXKddsqKuHZHVFRnkOWlBE6jMJd1pKryRPoMM+AUqenfF90qbYcv8bvVS6NS5ahCVN0r3T77lC+8eqEjvu5byK/byPmr6Er0rnOffP2BV3SgoazsFr7D9YllEouB6vEe6gSZzyS4RAaEtTn8lTUapZQrXZRS1vL1u/87X8EK6vxXAWelHNwoWT9Z5IUEeHifFChq+Vz1yt/TOG1IHRHw9k9GXCVDHZ30P/CS+fzfFLTxEJdd1sns2Bs2fS9sPEXCpFFIXAU4zEUXKKRo9mtxhoG5w2hk7XnQvs39h6FfQh3GjFtjAm/vgVDyeniH2XKaEBBrdpkz0gk86DlI3865gpPsyoL48Ly2KUnL/fjNJ0sNXK9rWMjQSE4Fqkjldxg=,iv:MnY2EsuBcPN+bThxT+GOQG3z2xa2SHMor5CgsmucUqQ=,tag:m+v+aWCJoslgGhvwYwEZtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWXhJZkQxeWJWK0NPYVQ1
            V0t1V1JJRkMzS3gzTzhpSWMyUVBPbERodGlnClJqNFdXcTJhSkpPdEQ2MCtJNjVp
            WVBCY0xuNGhaeVVabWpaVG8zcWdsWEkKLS0tIFltMW95anJ2MkhUM3VUMnpDdDFI
            aDBMUGlncG5xT0MvUUczdEtFMG96eTAKM9Zy2Nz+cPXHA+vsM0pjXO14nrDs9Gdn
            KZNfUe0KQmx3N04eoER7M/AQf/VvTuJsxtxHuEhVG1w1jMSCTaLxjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T09:23:11Z"
    mac: ENC[AES256_GCM,data:T3qLPgUKbsjOoP9xFUgc77+1IYb1rPnEWfrHM0mHK4JH++IdrgPkXJlmLfcELsZNEu0Wyo736BPYWqXKZ+CNSkOfQuit+qWT6LdSHmMgjkAN/eUUyP8V7edKbLoKNbUsjmIAfANM+Yin60pvhzJqAFYseahJEj6CUnE+A3jwsXQ=,iv:FZEYGK8P+JBr/3pxAOmQzHvMpsWyFxGRCPBfk5R8hFw=,tag:xo2hZafhZRAqDtY/jU0xOg==,type:str]
    version: 3.13.1
