apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postiz-uploads
  namespace: postiz
  labels:
    app.kubernetes.io/name: postiz-app
    app.kubernetes.io/instance: postiz
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
