apiVersion: v1
kind: Secret
metadata:
    name: postiz-postgresql
    namespace: postiz
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:7TDfuYHO,iv:/l/qnqWRisWQIb8SDmG72iqFgu2IjeZJtKj8EJRP7dU=,tag:EVYUF/+/Q9jwr9HRpsWL5g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:2ywUuj4y/768EqvVaTex,iv:Fpg8JDEszXOE/7dG/nNe29Dmp3zr/tvnErdMP0kQslg=,tag:LvGYgPBhkrlO2TtqWxCIdg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:x9jj3pfH,iv:dmaaeQbC4VB5M6f8hmCkU+yCWLLXDAg1MPycxV5wj0w=,tag:/QXt0BiEHNhgpiFAYB5lQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdlh6czcwa01aL3lIbnQ5
            SnNvaTd1NkZaL01PSFFPSTlvVmFKeWNYQ25NClBiVjYrWDlOSDBCMHFFdFg3OUZo
            TkRHM1QvWjkvRUxybjU4S2tpb0kwb1kKLS0tIDArdzlyVFdxN2hiTHlNSWg3N0Rt
            V1l1OEFETy95bU1kYVhpTC9pWTVoam8K7mP4GXQ1K9+uN3rGHbhYUsDaj6Ehhovo
            uaj5aAbwUleSiPgCLN9mi5MMw71f3Ct34xYlSwOYMehZLidnEsks9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T09:23:11Z"
    mac: ENC[AES256_GCM,data:2EtDNQl8WVOTo5ineSmu0B7ZHSRoewygB+C+ubHpX+35e7uTgu1VI2uYpSSZdbo50hN1mC5u9R2OGRF7oJbuqdsGzes4r5NFX1RBtYDRPV314GqwQ8riUR4PEQ9EhYBmoRwsdSmQn5FhJoKK0XsmdiV0gXgG+AHmCG1pXHlxZHU=,iv:bRl75UeYl8Pka8BPSNIY1ARs0Cmy9NITENr7tiXGOOY=,tag:TTCXjA+gk1/n7IRU2NvU8Q==,type:str]
    version: 3.13.1
