apiVersion: v1
kind: Secret
metadata:
    name: postiz-helm-values
    namespace: postiz
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:eHEtQYvIgADgnrErupsEqxljd1iqYPscRw3Rja3izKSJH5yOYVrwcpxeo9hRLbhRM4NmIKKtS8Ca3wx0T9IOfmUjFgwggU6fxnH9WqjVlqqc8qp7RNzY1A6JkmXTxtMfOpsHQYldULJQg0YGF0Gv9qQaTm/noagdyiyn5tXf3iFpcLxlWRnOo/oYX6pofLHvZ3PecSrs/YuRs9aly2S+693d6dBZwiyuFEimxR5Pl0M/Vn81g4MdFpDJqJDYNPPgBreGq6q2pOsxB2i4rttQpGZXFPX0oKxFZU98EXXk9hGWe78uoLu0dBtmZdgOK6JthtW42Lj9ri0wsLEDkNpgzoPI8oAbdqHtXq4LuJuaDGr2757LMK14pl9yzf+hchxCZcZSqovP/nlda5q+2jvufExipS3T1bZjxF0psS/QnZUm48IOTtUCIG+lpk1gfeXcsPvDa4IitK8eVoTi3oHzPNQ7GkQlNVAMAfDgeLCIe3UrNejvlwAbOub2QGh8dYU9aEeFRVtCjcfXA7O2eMWnm5jBFDzbDwtdy8d+4FLMsYXdRw21Aq3QjT0bRT9htgSqF38xVYzDkHrpCH6gZ1CiPXUu7c23hF9+Yf6q2MXBrsHAuVbSc0mNvAOuiUoddvZLpZT0,iv:/Q258TZZWBi/Zcmtvandr0UMQoW0PE6kOldzykuPN/0=,tag:nqKbKBldlrz1SZVdt2mBug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNFRYa2F2NDlhYjI2eXgr
            STdBbVdyOG85ZW1SR0xDeXJGY0hrZXBBS25FCll3dTVHQVZrd2pWbytibTdFbm9o
            T3JmMmI4ZittQzBza3dEd0xPRXB0Y1UKLS0tIFlNNG1MT2VaNVJWNmFSUHhkaU5B
            Y0tWOU9nQm9xenBLUFc3S1lIb0NONGcKpyV1+VvbXqBgk9RjlrauPuvOj8RZstDx
            LJgiFiImBlUNvz45rPEahsBML9DOxL3eVVRhASEchG2H4CQpSKlJ2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T10:17:52Z"
    mac: ENC[AES256_GCM,data:lIL2Is7UgO+U4QPGmJpJbdMWq+m3HQ0J3wiwMQW+9BQ7tUUvhgwB9SnFhpnloNT21i9ORfsFePxvkDZXbLanM+/wkvzfWaWe8izL9UmU6I1S9kUGg91rpxLAsbLELhYr0rYdBRdz65DVCo+oSO7ZEhGjNfGGNB7z5as3bblKLRs=,iv:LbvQbyR/aqE06Ot89miM8HI6ulYX+5Nyupv+gexO6Z8=,tag:SyIi2wOG87Bnf7SnxwURTA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: postiz-postgresql
    namespace: postiz
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:Ifk4VZ4i,iv:zflKUkP6U/38/g32YygInSLH4u7WGtkxSfht3lH5W/8=,tag:zi1BHhdWwVIQzNwzKB8pHg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:1VPGy7yzDCaTMDL0l6dJ,iv:OPV07H+qsFDNQDLniRTkAP0HbfXlFQL09dokCSNvtJ8=,tag:Z2fkwY7p6aSiqKrneVBZVw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:tVZ5MTiI,iv:4ETPVI+JQn/zW9mRR8ZOw1tmfVMcSO0kkf9tkse/JdA=,tag:KrKp4XDIEMkc1hn8+c6ktA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNFRYa2F2NDlhYjI2eXgr
            STdBbVdyOG85ZW1SR0xDeXJGY0hrZXBBS25FCll3dTVHQVZrd2pWbytibTdFbm9o
            T3JmMmI4ZittQzBza3dEd0xPRXB0Y1UKLS0tIFlNNG1MT2VaNVJWNmFSUHhkaU5B
            Y0tWOU9nQm9xenBLUFc3S1lIb0NONGcKpyV1+VvbXqBgk9RjlrauPuvOj8RZstDx
            LJgiFiImBlUNvz45rPEahsBML9DOxL3eVVRhASEchG2H4CQpSKlJ2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T10:17:52Z"
    mac: ENC[AES256_GCM,data:lIL2Is7UgO+U4QPGmJpJbdMWq+m3HQ0J3wiwMQW+9BQ7tUUvhgwB9SnFhpnloNT21i9ORfsFePxvkDZXbLanM+/wkvzfWaWe8izL9UmU6I1S9kUGg91rpxLAsbLELhYr0rYdBRdz65DVCo+oSO7ZEhGjNfGGNB7z5as3bblKLRs=,iv:LbvQbyR/aqE06Ot89miM8HI6ulYX+5Nyupv+gexO6Z8=,tag:SyIi2wOG87Bnf7SnxwURTA==,type:str]
    version: 3.13.1
