apiVersion: v1
kind: Secret
metadata:
    name: postiz-helm-values
    namespace: postiz
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:169lCa9ezDaUJYLmt+MrdmpYnnb+6Z/x0tvrHEXSttVVSEuy5cNeeTw52cO0btxFKKtRTWux8+JuHeDQvwNBzhuWXfPRqSk7/jAeUgAS160Cc5ugUotuXvL6M/AEpuEUXvRgDoty/B98VcOQMNySAB2n2CJ7hES1HqUO8PYVhntjwZeyq39RSgq5wkTSG7lPwe4GT9n2GksYRMiAxVKPn0aXESPWSQj8AQyIGTJR8kk7TahCgLbrEw++NAm448Il53b4CuVG4x9heGxa2ME/mkNGiJ+WVi1uWJM9M6XdJNgYOP4NQiRqfuEyqrgYe3Lx/zRbkJ3eeRPlEBVSFvyD2sE3oR5u6lWW5ThQUNc7KLMzWeS5Hh+7i8SU3JcQS1VnazFEhnYwrGEcVFRNuDki8giIfoG0OGjXDfqv2rs9TmODxGq9stFj32q2qqsjuDtwQ5Hc4H2pZPjgXwlE2cSzOOyceWV3n0zDl0a21ovwbpikQkDPXFxSfw/aaKjepjA=,iv:BcmdAKWkKiwmCL2szfhQa5qasIL0IlzMNNy7rC7AUsU=,tag:jBK40zGrKCnUNSaBwJLXqg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNFRYa2F2NDlhYjI2eXgr
            STdBbVdyOG85ZW1SR0xDeXJGY0hrZXBBS25FCll3dTVHQVZrd2pWbytibTdFbm9o
            T3JmMmI4ZittQzBza3dEd0xPRXB0Y1UKLS0tIFlNNG1MT2VaNVJWNmFSUHhkaU5B
            Y0tWOU9nQm9xenBLUFc3S1lIb0NONGcKpyV1+VvbXqBgk9RjlrauPuvOj8RZstDx
            LJgiFiImBlUNvz45rPEahsBML9DOxL3eVVRhASEchG2H4CQpSKlJ2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T09:55:23Z"
    mac: ENC[AES256_GCM,data:RgPybXS2UJSybpOKmouv11EVcZNkP22XfmHrTkpOh4+3cSpYIY1m5/6ztJYBcwAOQw3jrXY/Dw+y9OXfhRmUVZlDo0CFeRHAUetImV03QaQtVLEEyWkgUoUqdyn0Uh7ySQzZf0LdYCcXRxLJNoS7p+372TRej5sXas6oVufPU4M=,iv:Q56kBsIAT7cNs6ClXeJqEJktw4M52DnhVp5+X2Fl/Ug=,tag:39IIDGAIiJ2uyr2seHdqSA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: postiz-postgresql
    namespace: postiz
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:Ifk4VZ4i,iv:zflKUkP6U/38/g32YygInSLH4u7WGtkxSfht3lH5W/8=,tag:zi1BHhdWwVIQzNwzKB8pHg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:1VPGy7yzDCaTMDL0l6dJ,iv:OPV07H+qsFDNQDLniRTkAP0HbfXlFQL09dokCSNvtJ8=,tag:Z2fkwY7p6aSiqKrneVBZVw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:tVZ5MTiI,iv:4ETPVI+JQn/zW9mRR8ZOw1tmfVMcSO0kkf9tkse/JdA=,tag:KrKp4XDIEMkc1hn8+c6ktA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNFRYa2F2NDlhYjI2eXgr
            STdBbVdyOG85ZW1SR0xDeXJGY0hrZXBBS25FCll3dTVHQVZrd2pWbytibTdFbm9o
            T3JmMmI4ZittQzBza3dEd0xPRXB0Y1UKLS0tIFlNNG1MT2VaNVJWNmFSUHhkaU5B
            Y0tWOU9nQm9xenBLUFc3S1lIb0NONGcKpyV1+VvbXqBgk9RjlrauPuvOj8RZstDx
            LJgiFiImBlUNvz45rPEahsBML9DOxL3eVVRhASEchG2H4CQpSKlJ2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgjxqxjsgk0p46f0fyvnvxrd6sceuhqymyt4h5fsgaanrd2vt3yqpa0054
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T09:55:23Z"
    mac: ENC[AES256_GCM,data:RgPybXS2UJSybpOKmouv11EVcZNkP22XfmHrTkpOh4+3cSpYIY1m5/6ztJYBcwAOQw3jrXY/Dw+y9OXfhRmUVZlDo0CFeRHAUetImV03QaQtVLEEyWkgUoUqdyn0Uh7ySQzZf0LdYCcXRxLJNoS7p+372TRej5sXas6oVufPU4M=,iv:Q56kBsIAT7cNs6ClXeJqEJktw4M52DnhVp5+X2Fl/Ug=,tag:39IIDGAIiJ2uyr2seHdqSA==,type:str]
    version: 3.13.1
